baseURL = 'https://test.org/'
languageCode = 'en-us'
title = 'Ricky Anderson'
theme = 'PaperModX'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
title = 'ExampleSite'
description = "ExampleSite description"
keywords = ['Blog', 'Portfolio', 'PaperMod']
author = 'Ricky Anderson'

DateFormat = "2 January 2006"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
TocSide = 'right'
EnableInstantClick = true

disableSpecial1stPost = true
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[params.homeInfoParams]
Title = 'Ricky Anderson'
Content = "I'm a web developer mainly focused on backend web server.\nWelcome to my blog!"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/ricky_sonz"
[[params.socialIcons]]
name = "github"
url = "https://github.com/rickyson96"
